services:
  tile:
    image: pramsey/pg_tileserv
    restart: unless-stopped
    ports:
      - 7800:7800
    env_file:
      - ./db/.env
    depends_on:
      - db
  db:
    build: ./db
    env_file:
      - ./db/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
      - ./db/data:/data
volumes:
  pgdata:
