create table tree_cover_h3_2021 (
    h3_index                h3index, 
    mean_tree_cover_2021    double precision);

alter table tree_cover_h3_2021 add primary key (h3_index, mean_tree_cover_2021);

create table places (
    id          bigint generated by default as identity primary key ,
    name        text,
    geometry    geometry(Geometry, 4326)
);

create index places_name_idx on places (name);
create index places_geom_idx on places using gist(geometry);

